# Generated by Django 5.0.7 on 2024-07-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_amount_alter_orders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='unique_id',
            new_name='order_id',
        ),
    ]
