# Generated by Django 5.0.7 on 2024-07-26 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_unique_id_orders_order_id'),
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='items',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_item', to='products.product'),
            preserve_default=False,
        ),
    ]
