# Generated by Django 5.0.7 on 2024-07-28 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_order_by_orders_order_created_by'),
        ('products', '0003_rename_unique_code_product_product_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_created_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_id',
            new_name='order_number',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.orders'),
        ),
    ]
